dependencies {

    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

//    modImplementation("curse.maven:create-${create_curseforge_id}:${create_curseforge_file_id}")
//    modImplementation("curse.maven:selene-499980:4754433")
    compileOnly("curse.maven:intapi-${project.intapi_curseforge_id}:${project.intapi_curseforge_file_id_neoforge}")
    compileOnly("curse.maven:create-${project.create_curseforge_id_neoforge}:${project.create_curseforge_file_id_neoforge}")
    compileOnly("curse.maven:marvel-${project.marvel_curseforge_id}:${project.marvel_curseforge_file_id}")
    compileOnly("curse.maven:stellaris-${project.stellaris_curseforge_id}:${project.stellaris_curseforge_file_id}")
    compileOnly("curse.maven:aperture-${project.aperture_curseforge_id}:${project.aperture_curseforge_file_id}")
    compileOnly("curse.maven:inventory_pets-${project.inventory_pets_curseforge_id}:${project.inventory_pets_curseforge_file_id}")
    compileOnly("curse.maven:cataclysm-${project.cataclysm_curseforge_id}:${project.cataclysm_curseforge_file_id}")
    compileOnly("curse.maven:iaf-${project.iaf_curseforge_id}:${project.iaf_curseforge_file_id}")
    compileOnly("curse.maven:backpack-${project.backpack_curseforge_id}:${project.backpack_curseforge_file_id}")
//    compileOnly("curse.maven:regions_unexplored-${project.regions_unexplored_curseforge_id}:${project.regions_unexplored_curseforge_file_id}")
    compileOnly("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")
//
//    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.4'
//    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'


    annotationProcessor "org.spongepowered:mixin:0.8.7:processor"
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixin_extras}"))
}

architectury {
    common("fabric", "neoforge")
}

loom {
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "antarchy.refmap.json"
    }
}

jar {
    exclude "architectury.common.json"

    manifest {
        attributes 'Fabric-Loom-Remap': true
    }
}

sourcesJar {
    exclude "architectury.common.json"
}
