modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="apple_cows"
version="${version}"
displayName="Apple Cows"
authors="CraisinLord"
description= "Adds cute little apple cows!! Standalone from the Antarchy mod."
logoFile="../assets/antarchy_/apple_cows_logo.png"

[[dependencies.apple_cows]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"

[[dependencies.apple_cows]]
    modId="geckolib"
    type="required"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
